### ISSUE TITLE
Need to set CURLOPT_SSL_VERIFYPEER

### ISSUE THREAD

**Issue by thedangler** [urmaul/yii2-slack-log-route#2]
How can I set CURLOPT_SSL_VERIFYPEER to be 0?

**Comment by urmaul** [comment]
Why would you? Slack uses proper ssl certificates.

**Comment by thedangler** [comment]
On the production server, for some reason, if its not set to  0, it wont work.

**Comment by thedangler** [comment]
I'm trying to follow this: https://stackoverflow.com/questions/33795717/why-we-need-curlopt-ssl-verifypeer-in-windows

the link took me to download a .pem file.
I've changed my php.ini to us it.

Does you script or curl automatically try to use it?

**Comment by thedangler** [comment]
Fixed it. close the ticket if you want
